package scaleio

var metricKeys = [][]string{
	[]string{"pendingMovingOutBckRebuildJobs"},
	[]string{"secondaryVacInKb"},
	[]string{"numOfDevices"},
	[]string{"degradedHealthyCapacityInKb"},
	[]string{"activeMovingOutFwdRebuildJobs"},
	[]string{"bckRebuildWriteBwc", "numSeconds"},
	[]string{"bckRebuildWriteBwc", "totalWeightInKb"},
	[]string{"bckRebuildWriteBwc", "numOccured"},
	[]string{"failedCapacityInKb"},
	[]string{"primaryReadFromDevBwc", "numSeconds"},
	[]string{"primaryReadFromDevBwc", "totalWeightInKb"},
	[]string{"primaryReadFromDevBwc", "numOccured"},
	[]string{"BackgroundScannedInMB"},
	[]string{"activeMovingOutBckRebuildJobs"},
	[]string{"rfcacheReadsFromCache"},
	[]string{"pendingMovingInNormRebuildJobs"},
	[]string{"rfcacheReadsSkippedAlignedSizeTooLarge"},
	[]string{"failedVacInKb"},
	[]string{"primaryReadBwc", "numSeconds"},
	[]string{"primaryReadBwc", "totalWeightInKb"},
	[]string{"primaryReadBwc", "numOccured"},
	[]string{"pendingMovingInRebalanceJobs"},
	[]string{"pendingRebalanceCapacityInKb"},
	[]string{"rfcacheWritesSkippedHeavyLoad"},
	[]string{"unusedCapacityInKb"},
	[]string{"rfcacheAvgReadTime"},
	[]string{"semiProtectedCapacityInKb"},
	[]string{"totalReadBwc", "numSeconds"},
	[]string{"totalReadBwc", "totalWeightInKb"},
	[]string{"totalReadBwc", "numOccured"},
	[]string{"fwdRebuildReadBwc", "numSeconds"},
	[]string{"fwdRebuildReadBwc", "totalWeightInKb"},
	[]string{"fwdRebuildReadBwc", "numOccured"},
	[]string{"totalWriteBwc", "numSeconds"},
	[]string{"totalWriteBwc", "totalWeightInKb"},
	[]string{"totalWriteBwc", "numOccured"},
	[]string{"rfcacheWritesReceived"},
	[]string{"rmPendingAllocatedInKb"},
	[]string{"numOfVolumes"},
	[]string{"rfcacheIosOutstanding"},
	[]string{"protectedVacInKb"},
	[]string{"capacityAvailableForVolumeAllocationInKb"},
	[]string{"numOfMappedToAllVolumes"},
	[]string{"activeMovingRebalanceJobs"},
	[]string{"activeMovingInFwdRebuildJobs"},
	[]string{"bckRebuildCapacityInKb"},
	[]string{"pendingMovingRebalanceJobs"},
	[]string{"degradedHealthyVacInKb"},
	[]string{"semiProtectedVacInKb"},
	[]string{"pendingBckRebuildCapacityInKb"},
	[]string{"capacityLimitInKb"},
	[]string{"activeMovingCapacityInKb"},
	[]string{"activeMovingInNormRebuildJobs"},
	[]string{"rfcacheIosSkipped"},
	[]string{"inMaintenanceVacInKb"},
	[]string{"rfcacheReadsSkipped"},
	[]string{"numOfUnmappedVolumes"},
	[]string{"rfcacheWritesSkippedMaxIoSize"},
	[]string{"fixedReadErrorCount"},
	[]string{"atRestCapacityInKb"},
	[]string{"bckRebuildReadBwc", "numSeconds"},
	[]string{"bckRebuildReadBwc", "totalWeightInKb"},
	[]string{"bckRebuildReadBwc", "numOccured"},
	[]string{"rfcacheReadsSkippedInternalError"},
	[]string{"pendingMovingInBckRebuildJobs"},
	[]string{"activeBckRebuildCapacityInKb"},
	[]string{"rfcacheSourceDeviceWrites"},
	[]string{"spareCapacityInKb"},
	[]string{"rebalanceCapacityInKb"},
	[]string{"rfcacheIoErrors"},
	[]string{"normRebuildWriteBwc", "numSeconds"},
	[]string{"normRebuildWriteBwc", "totalWeightInKb"},
	[]string{"normRebuildWriteBwc", "numOccured"},
	[]string{"capacityInUseInKb"},
	[]string{"rfcacheReadsSkippedLowResources"},
	[]string{"rebalanceReadBwc", "numSeconds"},
	[]string{"rebalanceReadBwc", "totalWeightInKb"},
	[]string{"rebalanceReadBwc", "numOccured"},
	[]string{"rfcacheReadsSkippedMaxIoSize"},
	[]string{"thinCapacityInUseInKb"},
	[]string{"secondaryReadFromDevBwc", "numSeconds"},
	[]string{"secondaryReadFromDevBwc", "totalWeightInKb"},
	[]string{"secondaryReadFromDevBwc", "numOccured"},
	[]string{"rfcacheWritesSkippedInternalError"},
	[]string{"secondaryReadBwc", "numSeconds"},
	[]string{"secondaryReadBwc", "totalWeightInKb"},
	[]string{"secondaryReadBwc", "numOccured"},
	[]string{"secondaryReadFromRmcacheBwc", "numSeconds"},
	[]string{"secondaryReadFromRmcacheBwc", "totalWeightInKb"},
	[]string{"secondaryReadFromRmcacheBwc", "numOccured"},
	[]string{"rfcacheWritesSkippedStuckIo"},
	[]string{"inMaintenanceCapacityInKb"},
	[]string{"inUseVacInKb"},
	[]string{"rfcacheWritesSkippedCacheMiss"},
	[]string{"fwdRebuildCapacityInKb"},
	[]string{"thickCapacityInUseInKb"},
	[]string{"activeMovingInRebalanceJobs"},
	[]string{"degradedFailedCapacityInKb"},
	[]string{"BackgroundScanCompareCount"},
	[]string{"activeNormRebuildCapacityInKb"},
	[]string{"snapCapacityInUseInKb"},
	[]string{"rfcacheWriteMiss"},
	[]string{"rfcacheWritesSkippedLowResources"},
	[]string{"primaryReadFromRmcacheBwc", "numSeconds"},
	[]string{"primaryReadFromRmcacheBwc", "totalWeightInKb"},
	[]string{"primaryReadFromRmcacheBwc", "numOccured"},
	[]string{"numOfVtrees"},
	[]string{"rfacheReadHit"},
	[]string{"rfcacheSkippedUnlinedWrite"},
	[]string{"rfcacheAvgWriteTime"},
	[]string{"pendingMovingCapacityInKb"},
	[]string{"numOfSnapshots"},
	[]string{"pendingNormRebuildCapacityInKb"},
	[]string{"pendingFwdRebuildCapacityInKb"},
	[]string{"pendingMovingOutNormrebuildJobs"},
	[]string{"normRebuildCapacityInKb"},
	[]string{"rfcacheSourceDeviceReads"},
	[]string{"primaryWriteBwc", "numSeconds"},
	[]string{"primaryWriteBwc", "totalWeightInKb"},
	[]string{"primaryWriteBwc", "numOccured"},
	[]string{"numOfThickBaseVolumes"},
	[]string{"rfcacheReadsPending"},
	[]string{"fwdRebuildWriteBwc", "numSeconds"},
	[]string{"fwdRebuildWriteBwc", "totalWeightInKb"},
	[]string{"fwdRebuildWriteBwc", "numOccured"},
	[]string{"rfcacheReadsSkippedHeavyLoad"},
	[]string{"rfcacheReadMiss"},
	[]string{"activeRebalanceCapacityInKb"},
	[]string{"activeMovingInBckRebuildJobs"},
	[]string{"movingCapacityInKb"},
	[]string{"rfcacheReadsSkippedLockIos"},
	[]string{"unreachableUnusedCapacityInKb"},
	[]string{"pendingMovingInFwdRebuildJobs"},
	[]string{"rfcacheReadsReceived"},
	[]string{"numOfVolumesInDeletion"},
	[]string{"snapCapacityInUseOccupiedInKb"},
	[]string{"maxCapacityInKb"},
	[]string{"pendingMovingOutFwdRebuildJobs"},
	[]string{"activeFwdRebuildCapacityInKb"},
	[]string{"rfcacheReadsSkippedStuckIo"},
	[]string{"activeMovingOutNormRebuildJobs"},
	[]string{"protectedCapacityInKb"},
	[]string{"secondaryWriteBwc", "numSeconds"},
	[]string{"secondaryWriteBwc", "totalWeightInKb"},
	[]string{"secondaryWriteBwc", "numOccured"},
	[]string{"rfcacheWritePending"},
	[]string{"normRebuildReadBwc", "numSeconds"},
	[]string{"normRebuildReadBwc", "totalWeightInKb"},
	[]string{"normRebuildReadBwc", "numOccured"},
	[]string{"numOfThinBaseVolumes"},
	[]string{"degradedFailedVacInKb"},
	[]string{"thinCapacityAllocatedInKm"},
	[]string{"rebalanceWriteBwc", "numSeconds"},
	[]string{"rebalanceWriteBwc", "totalWeightInKb"},
	[]string{"rebalanceWriteBwc", "numOccured"},
	[]string{"primaryVacInKb"},
}
